spring:
  datasource:
    url: jdbc:mysql://10.0.4.56:3306/quartz1?characterEncoding=utf8&useUnicode=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia%2fShanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  quartz:
    job-store-type: jdbc
    jdbc.initialize-schema: never
    properties:
      org.quartz:
        scheduler:
          instanceId: AUTO
          instanceName: quartzscheduler1
        jobStore:
          isClustered: true

